-- B5 — Multi-Agent BI / Reporting Analyst
-- Queries the suite's OWN data (b1_documents, b2_leads_scored,
-- b3_approval_requests, b4_support_tickets) — real questions against real
-- rows generated by using B1-B4, rather than a separate synthetic dataset.

CREATE TABLE IF NOT EXISTS b5_bi_queries (
    id                  SERIAL PRIMARY KEY,
    question            TEXT NOT NULL,
    generated_sql       TEXT NOT NULL,
    validation_passed   BOOLEAN NOT NULL,
    rejection_reason    TEXT,
    row_count           INT,
    sample_results      JSONB NOT NULL DEFAULT '[]',   -- first ~20 rows, for the public replay
    chart_type          TEXT,                          -- 'bar' | 'line' | 'none'
    chart_x             TEXT,
    chart_y             TEXT,
    insight_summary     TEXT,
    trace               JSONB NOT NULL DEFAULT '[]',
    is_public_demo      BOOLEAN NOT NULL DEFAULT false,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
