"""SQL Generator → Validator (blocks unsafe SQL, THEN executes it under a
Postgres-enforced read-only transaction) → Chart → Insight Summarizer.

This is the suite's first project where an agent's output directly runs
against a live system, so the Validator isn't a nice-to-have — it's three
independent layers, any one of which alone should be enough to stop damage:

  1. STATIC CHECK — reject anything that isn't a single SELECT/WITH
     statement, reject a deny-list of write/DDL keywords, reject any table
     reference outside an explicit whitelist.
  2. DB-ENFORCED READ-ONLY — even if a write slipped past layer 1, the
     query runs inside a transaction with SET TRANSACTION READ ONLY, so
     Postgres itself refuses any write attempt.
  3. HARD ROLLBACK — the transaction is rolled back unconditionally after
     reading results, regardless of what happened, so nothing can persist.

Queries the suite's OWN tables (b1_documents, b2_leads_scored,
b3_approval_requests, b4_support_tickets) — real business questions against
real rows generated by using B1-B4, not a separate synthetic dataset.
"""
import re
from typing import TypedDict

from langgraph.graph import END, StateGraph
from sqlalchemy import text
from sqlalchemy.engine import Engine

from shared.llm_client import generate, generate_json

# The only tables the SQL Generator is told about, and the only ones the
# Validator will allow a query to reference. b1_chunks is deliberately
# excluded — it holds embedding vectors and full document text, not
# business-reportable data.
ALLOWED_TABLES = {
    "b1_documents": "id, filename, doc_type, chunk_count, ingested_at",
    "b1_rag_queries": "id, question, doc_type_routed, verified, retry_count, created_at",
    "b2_leads_scored": "id, company, target_profile, llm_score, formula_score, final_score, created_at",
    "b3_approval_requests": "id, request_type, requested_days, approver, status, notified, created_at, decided_at",
    "b4_support_tickets": "id, category, urgency, escalated, keyword_flagged, status, created_at",
}

FORBIDDEN_PATTERN = re.compile(
    r"\b(drop|delete|update|insert|alter|truncate|grant|revoke|create|exec|execute|"
    r"call|copy|vacuum|attach|detach|pragma|merge|replace|listen|notify|lock|do|"
    r"set|reset|comment)\b",
    re.IGNORECASE,
)

# Dangerous built-in functions that can be called without ever appearing
# after FROM/JOIN — the table-whitelist check alone can't catch these, since
# there's no table reference to check at all (e.g. `SELECT pg_terminate_backend(1)`).
DANGEROUS_FUNCTIONS_PATTERN = re.compile(
    r"\b(pg_terminate_backend|pg_cancel_backend|pg_reload_conf|pg_read_file|"
    r"pg_read_binary_file|pg_write_file|pg_ls_dir|pg_stat_file|pg_switch_wal|"
    r"pg_rotate_logfile|lo_import|lo_export|dblink|pg_sleep|set_config|current_setting)\b",
    re.IGNORECASE,
)

SQL_GENERATOR_SYSTEM = f"""You write a single read-only PostgreSQL SELECT query to answer a
business question, using ONLY these tables and columns:

{chr(10).join(f"- {t} ({cols})" for t, cols in ALLOWED_TABLES.items())}

Respond with ONLY a JSON object: {{"sql": "<the SQL query>", "explanation": "<one sentence on your approach>"}}
The query must be a single SELECT (or WITH ... SELECT) statement — no semicolons inside the query,
no other statement types, no tables other than the ones listed above. If the question can't be
answered from these tables, write a query that returns an empty/trivial result rather than
inventing a table or column that doesn't exist."""

CHART_SYSTEM = """Given a question and the columns of its query result, decide whether a bar or
line chart would help, or whether the result is better shown as a plain table. Respond with ONLY
a JSON object: {"chart_type": "bar"|"line"|"none", "x_column": "<column name or null>", "y_column": "<column name or null>"}
Use "line" only for a genuine time series (a date/timestamp column on the x-axis). Use "none" for
a single-value result, or when no column pairing makes a sensible chart."""

INSIGHT_SYSTEM = """You write a 2-3 sentence plain-English summary of what a query result shows,
for someone who doesn't want to read a data table. Be specific with the actual numbers you're
given — do not round vaguely or hedge if the data is precise. Do not speculate beyond what the
result actually shows.

CRITICAL: you are only ever shown the output of a read-only SELECT query. It is IMPOSSIBLE for
this query to have deleted, updated, inserted, or changed anything — describe only what the
returned rows/columns show, never narrate an action (deleting, updating, fixing, removing) as
having happened, even if the original question asked for one. If the SQL is a trivial placeholder
(e.g. "SELECT 1") that doesn't actually answer the question, say plainly that the question
couldn't be answered from the available data — do not invent a plausible-sounding result to match
what the question asked for."""


class BIState(TypedDict, total=False):
    question: str
    generated_sql: str | None
    sql_explanation: str | None

    validation_passed: bool
    rejection_reason: str | None

    columns: list[str]
    rows: list[dict]
    row_count: int

    chart_type: str | None
    chart_x: str | None
    chart_y: str | None

    insight_summary: str | None

    trace: list[dict]


def sql_generator_node(state: BIState) -> dict:
    try:
        result = generate_json(SQL_GENERATOR_SYSTEM, state["question"])
        sql = result.get("sql", "").strip()
        explanation = result.get("explanation", "")
    except Exception as e:
        sql, explanation = "", f"SQL generation failed: {e}"

    return {
        "generated_sql": sql,
        "sql_explanation": explanation,
        "trace": [{"agent": "sql_generator", "status": "done", "detail": f"generated: {sql[:80]}"}],
    }


def _validate_sql(sql: str) -> tuple[bool, str | None]:
    if not sql:
        return False, "no SQL was generated"

    stripped = sql.strip().rstrip(";").strip()
    if ";" in stripped:
        return False, "multiple statements are not allowed"

    lowered = stripped.lower()
    if not (lowered.startswith("select") or lowered.startswith("with")):
        return False, "only SELECT (or WITH ... SELECT) queries are allowed"

    if FORBIDDEN_PATTERN.search(stripped):
        return False, "query contains a disallowed keyword (write/DDL operations are blocked)"

    if DANGEROUS_FUNCTIONS_PATTERN.search(stripped):
        return False, "query calls a disallowed system function"

    # CTE aliases (WITH x AS (...), y AS (...)) are not real tables and must
    # not be checked against the table whitelist — only what they SELECT FROM
    # matters, which the same regex below already picks up separately.
    cte_names = set(re.findall(r"with\s+([a-zA-Z_][a-zA-Z0-9_]*)\s+as\s*\(", lowered))
    cte_names |= set(re.findall(r",\s*([a-zA-Z_][a-zA-Z0-9_]*)\s+as\s*\(", lowered))

    referenced_tables = set(re.findall(r"(?:from|join)\s+([a-zA-Z_][a-zA-Z0-9_]*)", lowered))
    disallowed = referenced_tables - set(ALLOWED_TABLES.keys()) - cte_names
    if disallowed:
        return False, f"query references table(s) not in the allowed list: {', '.join(disallowed)}"

    return True, None


def build_validator_node(engine: Engine):
    def validator_node(state: BIState) -> dict:
        sql = state.get("generated_sql", "")
        passed, reason = _validate_sql(sql)

        if not passed:
            return {
                "validation_passed": False,
                "rejection_reason": reason,
                "trace": [{"agent": "validator", "status": "done", "detail": f"rejected: {reason}"}],
            }

        # Layer 2 + 3: even validated SQL runs inside a transaction that's
        # explicitly told to be read-only at the Postgres level, and gets
        # rolled back unconditionally afterward — belt AND suspenders on top
        # of the static check above.
        stripped_sql = sql.strip().rstrip(";")
        try:
            with engine.connect().execution_options(isolation_level="READ COMMITTED") as conn:
                trans = conn.begin()
                try:
                    conn.execute(text("SET TRANSACTION READ ONLY"))
                    result = conn.execute(text(stripped_sql))
                    columns = list(result.keys())
                    rows = [dict(r) for r in result.mappings().all()]
                finally:
                    trans.rollback()  # unconditional — nothing persists, success or failure
        except Exception as e:
            return {
                "validation_passed": False,
                "rejection_reason": f"query execution failed: {e}",
                "trace": [{"agent": "validator", "status": "done", "detail": f"execution error: {e}"}],
            }

        return {
            "validation_passed": True,
            "columns": columns,
            "rows": rows,
            "row_count": len(rows),
            "trace": [{"agent": "validator", "status": "done", "detail": f"passed, {len(rows)} row(s) returned"}],
        }

    return validator_node


def validator_router(state: BIState) -> str:
    return "continue" if state.get("validation_passed") else "end"


def chart_node(state: BIState) -> dict:
    columns = state.get("columns", [])
    rows = state.get("rows", [])
    if not rows or len(columns) < 2:
        return {
            "chart_type": "none",
            "trace": [{"agent": "chart", "status": "done", "detail": "no chart — too few columns/rows"}],
        }

    try:
        result = generate_json(
            CHART_SYSTEM,
            f"Question: {state['question']}\nColumns: {columns}\nSample row: {rows[0]}",
        )
        chart_type = result.get("chart_type", "none")
        if chart_type not in ("bar", "line", "none"):
            chart_type = "none"
        x_col, y_col = result.get("x_column"), result.get("y_column")
    except Exception:
        chart_type, x_col, y_col = "none", None, None

    return {
        "chart_type": chart_type,
        "chart_x": x_col,
        "chart_y": y_col,
        "trace": [{"agent": "chart", "status": "done", "detail": f"chart_type: {chart_type}"}],
    }


def insight_summarizer_node(state: BIState) -> dict:
    rows = state.get("rows", [])
    if not rows:
        summary = "The query ran successfully but returned no rows."
    else:
        sample = rows[:10]
        summary = generate(
            INSIGHT_SYSTEM,
            f"Question: {state['question']}\nSQL that was actually run: {state.get('generated_sql')}\n"
            f"Total rows: {state['row_count']}\nSample data: {sample}",
            max_tokens=250,
        )

    return {
        "insight_summary": summary,
        "trace": [{"agent": "insight_summarizer", "status": "done", "detail": "summarized results"}],
    }


def build_graph(engine: Engine):
    workflow = StateGraph(BIState)
    workflow.add_node("sql_generator", sql_generator_node)
    workflow.add_node("validator", build_validator_node(engine))
    workflow.add_node("chart", chart_node)
    workflow.add_node("insight_summarizer", insight_summarizer_node)

    workflow.set_entry_point("sql_generator")
    workflow.add_edge("sql_generator", "validator")
    workflow.add_conditional_edges("validator", validator_router, {"continue": "chart", "end": END})
    workflow.add_edge("chart", "insight_summarizer")
    workflow.add_edge("insight_summarizer", END)

    return workflow.compile()